trigger:
  - master

# Używamy agenta hostowanego przez Microsoft. Działa to, ponieważ projekt jest teraz prywatny.
pool:
  name: Default
steps:
- script: |
    java -version
    mvn -version
  displayName: 'Sprawdź wersje Java i Maven (debug)'

# steps:
# - task: JavaToolInstaller@0
#   displayName: 'Install Java 21'
#   inputs:
#     versionSpec: '21'
#     jdkArchitectureOption: 'x64'
#         # 'PreInstalled' jest właściwą opcją dla agentów hostowanych przez Microsoft
#     jdkSourceOption: 'PreInstalled'

- task: Maven@4
  displayName: 'Build and Run Cucumber Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify -Dtest=CucumberTestRunner'
    options: '-Dmaven.test.failure.ignore=true'

- task: PublishTestResults@2
  displayName: 'Publish JUnit Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: false

- task: PublishAllureReport@2
  displayName: 'Publish Allure Report'
  condition: succeededOrFailed()
  inputs:
    allureResults: '$(System.DefaultWorkingDirectory)/target/allure-results'
    # Nie ma potrzeby definiowania targetDir, zadanie samo zarządza raportem
    # i publikuje go w zakładce 'Allure Report' w potoku.

  # Publikowanie jako artefakt nie jest już konieczne, gdy używasz PublishAllureReport@2,
  # ponieważ to zadanie samo integruje raport z interfejsem Azure DevOps.
  # Możesz odkomentować, jeśli nadal chcesz mieć pliki raportu jako artefakt do pobrania.
  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Allure Report Artifact'
  #   condition: succeededOrFailed()
  #   inputs:
  #     pathToPublish: '$(Build.ArtifactStagingDirectory)/allure-report' # Ścieżka może wymagać dostosowania
  #     artifactName: 'AllureReport'
  #     publishLocation: 'Container'
