trigger:
  - master

pool:
  name: Default
steps:
- task: Maven@4
  displayName: 'Build and Run Cucumber Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify -Dtest=CucumberTestRunner'
    options: '-Dmaven.test.failure.ignore=true'

- script: 
    mvn allure generate --single-file allure-results




# - task: PublishTestResults@2
#   displayName: 'Publish JUnit Test Results'
#   condition: succeededOrFailed()
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     mergeTestResults: true
#     failTaskOnFailedTests: false

# - task: PublishAllureReport@2
#   displayName: 'Publish Allure Report'
#   condition: succeededOrFailed()
#   inputs:
#     allureResults: '$(System.DefaultWorkingDirectory)/target/allure-results'
    # Nie ma potrzeby definiowania targetDir, zadanie samo zarządza raportem
    # i publikuje go w zakładce 'Allure Report' w potoku.

  # Publikowanie jako artefakt nie jest już konieczne, gdy używasz PublishAllureReport@2,
  # ponieważ to zadanie samo integruje raport z interfejsem Azure DevOps.
#   # Możesz odkomentować, jeśli nadal chcesz mieć pliki raportu jako artefakt do pobrania.
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Allure Report Artifact'
#   condition: succeededOrFailed()
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)' # Ścieżka może wymagać dostosowania
#     artifactName: 'AllureReport'
#     publishLocation: 'Container'
