#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#
#spring.h2.console.enabled=true
#spring.datasource.generate-unique-name=false
#spring.datasource.url=jdbc:h2:file:./demodb
#spring.datasource.name=game_library

spring:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    url: 'jdbc:h2:file:./demodb'
    name: game_library
    username:
    password:
my.prop: 'test'